DROP TABLE IF EXISTS Account;
CREATE TABLE Account (
AccountId LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
Balance DECIMAL(19,4)
);

DROP TABLE IF EXISTS AccountTransaction;
CREATE TABLE AccountTransaction (
TransactionId LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
Amount DECIMAL(19,4) NOT NULL,
TrxTimeStamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FromAccountId LONG,
ToAccountId LONG,
Purpose VARCHAR(500) NOT NULL
);
CREATE UNIQUE INDEX idx_accTrx on AccountTransaction(FromAccountId,TrxTimeStamp);

--TEST DATA
INSERT INTO Account (Balance) VALUES (100000.0000);
INSERT INTO Account (Balance) VALUES (200000.0000);
INSERT INTO Account (Balance) VALUES (300000.0000);
INSERT INTO Account (Balance) VALUES (400000.0000);
INSERT INTO Account (Balance) VALUES (200.0000);
INSERT INTO Account (Balance) VALUES (100.0000);
INSERT INTO Account (Balance) VALUES (700.0000);
INSERT INTO Account (Balance) VALUES (900.0000);
INSERT INTO Account (Balance) VALUES (900.0000);

INSERT INTO Account (Balance) VALUES (1050.0000);
INSERT INTO Account (Balance) VALUES (1150.0000);
